### ISSUE TITLE
Provide FastInfoset-*-sources.jar required by project eclipse-ee4j/jaxb-ri

### ISSUE THREAD

**Issue by rsearls** [eclipse-ee4j/jaxb-fi#114]
module fastinfoset needs to generate a FastInfoset-*-sources.jar archive.
Project https://github.com/eclipse-ee4j/jaxb-ri.git requires this source
jar to successfully build module jaxb-ri/bundles/osgi/osgi generated classes.

**Comment by lukasj** [comment]
Pass -Poss-release to the build to get sources as well as javadoc jars. Or am I missing something?

**Comment by rsearls** [comment]
@lukasj  please clarify your statement above.  Is there some action I am to take?

**Comment by lukasj** [comment]
mvn install -Poss-release

**Comment by rsearls** [comment]
@lukgpg:  "mvn install -Poss-release" does not work for me.  I get error.

 no default secret key: No secret key
gpg: signing failed: No secret key

**Comment by lukasj** [comment]
what have you tried to resolve this?

see [the build command](https://github.com/eclipse-ee4j/jaxb-fi/blob/master/.github/workflows/maven.yml#L37) or the documentation of [the gpg plugin](https://maven.apache.org/plugins/maven-gpg-plugin/sign-mojo.html#skip). One can also [set up GPG signing](https://central.sonatype.org/publish/requirements/gpg/) on his end

**Comment by rsearls** [comment]
@lukasj    OK I created a key and this cmd (mvn install -Poss-release) runs successfully.
What next?

**Comment by lukasj** [comment]
> What next?

I don't know. Check the content of `target` folders or of the local maven repository after running the build to see what is there or see what the failure is? Keep in mind that I'm not sitting next to you nor I can see the output of the build, I don't know which OS/java version/maven version you use etc there are simply too many variables I'm guessing

**Comment by rsearls** [comment]
There are no build or test failures.
The needed *--sources.jar.* archives are generated and install in my local repo.
This looks good to me.

**Comment by lukasj** [comment]
closing per the last comment
