### ISSUE TITLE
printStackTrace in SAXDocumentParser

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-fi#33]
Hi,

this is a minor issue, but inflates console output.

Location:
com.sun.xml.fastinfoset.sax.SAXDocumentParser.parse(InputSource)

Best regards,
Kristian
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[current]

**Comment by lukasj** [comment]
already fixed
